### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by DenisKent** [FACN4/week8FantasyCoin#2]
## Phase 1

- [x] Set up express server
- [ ] Set up handlebars for all 4 pages
- [x] Set up Heroku & Travis
- [ ] Set up database and basic DB queries
